[package]
name = "gotham-repro"
version = "0.1.0"
authors = ["Forb.Jok <forbjok@gmail.com>"]

[dependencies]
gotham = { git = "https://github.com/gotham-rs/gotham.git" }
gotham_derive = { git = "https://github.com/gotham-rs/gotham.git" }
hyper = "~0.11.11"
slog = "~2.1.1"
